# Generated by Django 5.2.12 on 2026-04-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activerole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blocked_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invite_link', models.CharField(default='', max_length=500)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('total_amount', models.BigIntegerField()),
                ('remaining_amount', models.BigIntegerField()),
                ('collected_users', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'giveaway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Para',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paralar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollar', models.BigIntegerField(default=0)),
                ('diamond', models.BigIntegerField(default=0)),
                ('himoya', models.IntegerField(default=0)),
                ('hujjat', models.IntegerField(default=0)),
                ('qotildan_himoya', models.IntegerField(default=0)),
                ('osishdan_himoya', models.IntegerField(default=0)),
                ('miltiq', models.IntegerField(default=0)),
                ('doridan_himoya', models.IntegerField(default=0)),
                ('maska', models.IntegerField(default=0)),
                ('verbana', models.IntegerField(default=0)),
                ('wins', models.BigIntegerField(default=0)),
                ('slip_himoya', models.IntegerField(default=0)),
                ('geroy_himoya', models.IntegerField(default=0)),
                ('games_count', models.BigIntegerField(default=0)),
                ('on_himoya', models.BooleanField(default=True)),
                ('on_hujjat', models.BooleanField(default=True)),
                ('on_qotildan_himoya', models.BooleanField(default=True)),
                ('on_osishdan_himoya', models.BooleanField(default=True)),
                ('on_miltiq', models.BooleanField(default=True)),
                ('on_verbana', models.BooleanField(default=True)),
                ('on_doridan_himoya', models.BooleanField(default=True)),
                ('on_maska', models.BooleanField(default=True)),
                ('on_slip_himoya', models.BooleanField(default=True)),
                ('on_geroy_himoya', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transfers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('full_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('mention', models.TextField()),
                ('lang', models.CharField(default='uz', max_length=2)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VipUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vipuser',
                'managed': False,
            },
        ),
    ]
