# Generated by Django 6.0.4 on 2026-05-07 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=20)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('with_miltiq', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_processed', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'balance_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blockgrousp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChangeDiamondGiveAway',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('amount', models.BigIntegerField()),
                ('collected_users', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'changediamondgiveaway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommandPermissionsChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('start_cmd', models.CharField(max_length=10)),
                ('stop_cmd', models.CharField(max_length=10)),
                ('game_cmd', models.CharField(max_length=10)),
                ('top1_cmd', models.CharField(max_length=10)),
                ('top7_cmd', models.CharField(max_length=10)),
                ('top30_cmd', models.CharField(max_length=10)),
                ('gtop1_cmd', models.CharField(max_length=10)),
                ('gtop7_cmd', models.CharField(max_length=10)),
                ('gtop30_cmd', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commandpermissionschat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.BigIntegerField()),
                ('phase', models.CharField(default='waiting', max_length=10)),
                ('mode', models.CharField(default='classic', max_length=20)),
                ('bot_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameModeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('mode_name', models.CharField(default='classic', max_length=20)),
            ],
            options={
                'db_table': 'gamemodeset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamePhase',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phase_type', models.CharField(max_length=10)),
                ('number', models.BigIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_end', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gamephase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=70)),
                ('is_alive', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('deaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_sayed_last_word', models.BooleanField(default=False)),
                ('can_heal_self', models.BooleanField(default=True)),
                ('can_protection_self', models.BooleanField(default=True)),
                ('can_document_self', models.BooleanField(default=True)),
                ('can_investigate_self', models.BooleanField(default=True)),
                ('can_osishdan_himoya', models.BooleanField(default=True)),
                ('can_osishdan_himoya_adv', models.BooleanField(default=True)),
                ('can_slip_himoya', models.BooleanField(default=True)),
                ('is_sleep', models.BooleanField(default=False)),
                ('is_osilmas', models.BooleanField(default=False)),
                ('osildi', models.BooleanField(default=False)),
                ('missed_nights', models.BigIntegerField(default=0)),
                ('should_choose_card', models.BooleanField(default=False)),
                ('is_really_winner', models.BooleanField(default=False)),
                ('last_visited_user_id', models.BigIntegerField(blank=True, null=True)),
                ('maxsus_raqam', models.BigIntegerField(blank=True, null=True)),
                ('win', models.BooleanField(default=False)),
                ('is_actioned', models.BooleanField(default=False)),
                ('life', models.IntegerField(default=100)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'gameplayer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSetListRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('blacklist', models.TextField(default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamesetlistroles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSetPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('anonim_ovoz_berish', models.BooleanField(default=False)),
                ('leave_qilish', models.BooleanField(default=True)),
                ('last_word_say', models.BooleanField(default=True)),
                ('frendly_fire', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamesetpermissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSetRoleConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField()),
                ('player_count', models.IntegerField()),
                ('roles_count', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_set_role_configs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSetTime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('day_time', models.BigIntegerField(default=45)),
                ('night_time', models.BigIntegerField(default=45)),
                ('vote_time', models.BigIntegerField(default=30)),
                ('like_time', models.BigIntegerField(default=30)),
                ('word_time', models.BigIntegerField(default=30)),
                ('auto_start_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'game_sets_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameSetWeapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('himoya', models.BooleanField(default=True)),
                ('hujjat', models.BooleanField(default=True)),
                ('qotildan_himoya', models.BooleanField(default=True)),
                ('ovozdan_himoya', models.BooleanField(default=True)),
                ('miltiq', models.BooleanField(default=True)),
                ('doridan_himoya', models.BooleanField(default=True)),
                ('slip_himoya', models.BooleanField(default=True)),
                ('maska', models.BooleanField(default=True)),
                ('geroy', models.BooleanField(default=True)),
                ('active_role', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gamesetweapons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GamingOnChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('can_gaming', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gamingonchat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GazabdorPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gazabdorpick',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeroyAction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geroyaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeroyMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geroymarket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geroys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('patron', models.IntegerField(default=10)),
                ('level', models.IntegerField(default=1)),
                ('himoya', models.IntegerField(default=0)),
                ('ball', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'geroys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GiveTopChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gived_at', models.DateTimeField(auto_now_add=True)),
                ('give_type', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'givetopchat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reset_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'groupbalance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupGiveSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('diamond', models.BigIntegerField(default=0)),
                ('dollar', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groupgiveset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupMoreSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('mafning_ovozi', models.BooleanField(default=True)),
                ('adv_view', models.BooleanField(default=True)),
                ('max_players', models.BigIntegerField(default=30)),
                ('rollarni_guruhlash', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'groupmoreset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MafiaRolesCountSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('maf3', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mafia_roles_count_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NickList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nicklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NickListItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'nicklistitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NickModeSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'nickmodeset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenSandiqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sandiq_type', models.CharField(default='mega', max_length=20)),
            ],
            options={
                'db_table': 'opensandiqs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayersGameBall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'playersgameball',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransfersReportsChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('report_diamond', models.BooleanField(default=True)),
                ('report_dollar', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transfersreportschat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vote',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoteLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_like', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'votelike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WolfOrFoxSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('wolf_or_fox', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wolfortfoxset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WriteGroupPermis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('night', models.CharField(default='alive', max_length=20)),
                ('day', models.CharField(default='alive', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'writegrouppermis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_login_tokens',
            },
        ),
    ]
