# Generated by Django 6.0.4 on 2026-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_action_balancetransaction_blockgroups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogintoken',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
