# Generated by Django 6.0.4 on 2026-05-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_adminlogintoken_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('roles', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_role_order',
                'managed': True,
            },
        ),
    ]
