# Generated by Django 5.2.12 on 2026-09-13 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_fitnachi_all_group_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaChannel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('invite_link', models.CharField(max_length=512)),
                ('accepts_join_requests', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cinema_subscription_channel',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CinemaJoinRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('requested_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'cinema_subscription_join_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CinemaMovie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('file_id', models.CharField(max_length=512)),
                ('message_text', models.TextField(blank=True, default='')),
                ('request_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cinema_movie',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CinemaPlan',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('price_diamonds', models.BigIntegerField(default=100)),
                ('duration_days', models.IntegerField(default=30)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cinema_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CinemaPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('price_diamonds', models.BigIntegerField()),
                ('duration_days', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cinema_purchase',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CinemaSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cinema_subscription',
                'managed': False,
            },
        ),
    ]
